"""empty message

Revision ID: f389b2c26d61
Revises:
Create Date: 2025-07-13 17:49:37.826337

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f389b2c26d61"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "url_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original", sa.String(length=500), nullable=False),
        sa.Column("short", sa.String(length=500), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("url_map", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_url_map_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("url_map", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_url_map_timestamp"))

    op.drop_table("url_map")
    # ### end Alembic commands ###
